FROM node:10
ARG NODE_ENV=development
ENV NODE_PATH=/src/ 

# RUN apk --no-cache add python make g++
# RUN mkdir /usr/src/app
# WORKDIR /src/ 
# RUN ls /
# RUN ls /src/
# RUN npm install
# RUN npm run watch-poll